syntax = "proto3";

import 'lib/src/monorepo/module/asset/name.proto';
import 'lib/src/monorepo/module/asset/registrations.proto';
import 'lib/src/monorepo/module/asset/compression.proto';
import 'lib/src/monorepo/module/asset/type.proto';

package runtime.aot.monorepo.module.asset.reflection;


message ModuleAssetReflection {
  runtime.aot.monorepo.module.asset.name.ModuleAssetNameReflection name = 1;
  runtime.aot.monorepo.module.asset.type.ModuleAssetTypeEnum type = 2;
  // Enums unfortunately need to be broken out into their own package to avoid naming  conflicts
  runtime.aot.monorepo.module.asset.registrations.ModuleAssetRegistrationEnum enumeration = 3;
  string version = 4;
  runtime.aot.monorepo.module.asset.compression.ModuleAssetCompressionEnum compression = 5;
}



message GoogleCloudStorageModuleAssetNameReflection {
  // These are duplicated from the ModuleAssetNameReflection bc messages cant extend each-other
  string value = 1;
  bool fuzzy = 2;
  bool assembled = 3;
    runtime.aot.monorepo.module.asset.name.ModuleAssetNameConventionEnum convention = 4;

  // No GCP Name Specifics atm
}

message GoogleCloudStorageModuleAssetReflection {
  // These are duplicated from the ModuleAssetReflection bc messages cant extend each-other
  GoogleCloudStorageModuleAssetNameReflection name = 1;
  runtime.aot.monorepo.module.asset.type.ModuleAssetTypeEnum type = 2;
  runtime.aot.monorepo.module.asset.registrations.ModuleAssetRegistrationEnum enumeration = 3;
  string version = 4;
  runtime.aot.monorepo.module.asset.compression.ModuleAssetCompressionEnum compression = 5;

  // No GCP Specifics atm
}

message GitHubReleasesModuleAssetReflection {

  // These are duplicated from the ModuleAssetReflection bc messages cant extend each-other
  GitHubReleasesModuleAssetNameReflection name = 1;
  runtime.aot.monorepo.module.asset.type.ModuleAssetTypeEnum type = 2;
  runtime.aot.monorepo.module.asset.registrations.ModuleAssetRegistrationEnum enumeration = 3;
  string version = 4;
  runtime.aot.monorepo.module.asset.compression.ModuleAssetCompressionEnum compression = 5;

  // These are GH Specific
  string repository = 8;
  string tag = 9;
  bool overwrite = 10;
}


message GitHubReleasesModuleAssetNameReflection {
  // These are duplicated from the ModuleAssetNameReflection bc messages cant extend each-other
  string value = 1;
  bool fuzzy = 2;
  bool assembled = 3;
    runtime.aot.monorepo.module.asset.name.ModuleAssetNameConventionEnum convention = 4;

  // No GCP Name Specifics atm
}


