syntax = "proto3";

import "lib/src/core/root/grpc/shared/models/cancellation.proto";
import "lib/src/core/root/grpc/shared/models/user.proto";
package runtime.aot.machine_learning.text.detection.error.vertex;

message UndetectedTextualContentDomain {
  string value = 1;
  // optional user
  runtime.aot.core.UserProfile user = 2;
  // note: this is the os_identifier
  string os = 3;
}

enum TextualContentDomainErrorDetectionType {
  ERROR = 0;
  UNKNOWN = 1;
}

message TextualContentDomainErrorDetection {
  runtime.aot.core.Cancellation cancellation = 1;
  TextualContentDomainErrorDetectionType type = 2;
}

// ========================================================================
// Initialized Class.
// ========================================================================

message TextualContentDomainErrorDetectionInitialization {
}


message InitializedTextualContentDomainErrorDetection {
}
