syntax = "proto3";

import "lib/src/core/root/grpc/shared/models/cancellation.proto";
import "lib/src/core/root/grpc/shared/models/user.proto";

package runtime.aot.machine_learning.text.technical_language.code.detectors.language.vertex;

message UndetectedCodeLanguage {
  string value = 1;
  // optional user
  runtime.aot.core.UserProfile user = 2;
  // note: this is the os_identifier
  string os = 3;
}

enum CodeLanguageDetectionType {
  CSX = 0;
  CS = 1;
  HTML = 2;
  HTM = 3;
  SHTML = 4;
  XHTML = 5;
  HS = 6;
  HS_BOOT = 7;
  HSIG = 8;
  CPP = 9;
  CC = 10;
  CP = 11;
  CXX = 12;
  C = 13;
  H = 14;
  HH = 15;
  HPP = 16;
  HXX = 17;
  INL = 18;
  IPP = 19;
  IXX = 20;
  CPPM = 21;
  CSV = 22;
  DOC = 23;
  DOCM = 24;
  DOCX = 25;
  EXE = 26;
  GIF = 27;
  ICO = 28;
  JPE = 29;
  JPEG = 30;
  JPG = 31;
  JPGM = 32;
  JPGV = 33;
  LOG = 34;
  MP2 = 35;
  MP2A = 36;
  MP3 = 37;
  MP4 = 38;
  MP4A = 39;
  OGA = 40;
  OGG = 41;
  OGV = 42;
  OGX = 43;
  PPT = 44;
  PPTX = 45;
  PPTM = 46;
  QT = 47;
  TEXT = 48;
  TIF = 49;
  TIFF = 50;
  TXT = 51;
  WAV = 52;
  WEBA = 53;
  WEBM = 54;
  WEBP = 55;
  XLA = 56;
  XLAM = 57;
  XLC = 58;
  XLM = 59;
  XLS = 60;
  XLSB = 61;
  XLSM = 62;
  XLSX = 63;
  XLT = 64;
  XLTM = 65;
  XLTX = 66;
  PDF = 67;
  PNG = 68;
  RPM = 69;
  ZIP = 70;
  WOFF = 71;
  WOFF2 = 72;
  SVGZ = 73;
  BIN = 74;
  BMP = 75;
  EOT = 76;
  GZ = 77;
  JAR = 78;
  MPKG = 79;
  AI = 80;
  EPS = 81;
  DMG = 82;
  LIST = 83;
  RTX = 84;
  URI = 85;
  URIS = 86;
  URLS = 87;
  CSS = 88;
  DART = 89;
  JAVA = 90;
  BSH = 91;
  JS = 92;
  JSX = 93;
  MJS = 94;
  HTC = 95;
  JSON = 96;
  IPYNB = 97;
  GLTF = 98;
  JSONML = 99;
  PS = 100;
  SSML = 101;
  WASM = 102;
  RTF = 103;
  CCO = 104;
  PL = 105;
  PC = 106;
  PM = 107;
  PMC = 108;
  POD = 109;
  T = 110;
  XML = 111;
  TLD = 112;
  DTML = 113;
  RNG = 114;
  RSS = 115;
  OPML = 116;
  SVG = 117;
  XAML = 118;
  SUBLIME_SNIPPET = 119;
  TMLANGUAGE = 120;
  TMPREFERENCES = 121;
  TMSNIPPET = 122;
  TMTHEME = 123;
  CSPROJ = 124;
  FSPROJ = 125;
  SQLPROJ = 126;
  VBPROJ = 127;
  VCPROJ = 128;
  VCXPROJ = 129;
  DAE = 130;
  PROPS = 131;
  TARGETS = 132;
  XSD = 133;
  XSL = 134;
  XSLT = 135;
  ECMA = 136;
  NODE = 137;
  PHP = 138;
  PHP3 = 139;
  PHP4 = 140;
  PHP5 = 141;
  PHP7 = 142;
  PHP8 = 143;
  PHPS = 144;
  PHPT = 145;
  PHTML = 146;
  PY = 147;
  PY3 = 148;
  PYW = 149;
  PYI = 150;
  PYX = 151;
  PYX_IN = 152;
  PXD = 153;
  PXD_IN = 154;
  PXI = 155;
  PXI_IN = 156;
  RPY = 157;
  CPY = 158;
  GYP = 159;
  GYPI = 160;
  VPY = 161;
  SMK = 162;
  WSCRIPT = 163;
  BAZEL = 164;
  BZL = 165;
  PYC = 166;
  CLASS = 167;
  P = 168;
  PAS = 169;
  CURL = 170;
  MCURL = 171;
  GO = 172;
  SWIFT = 173;
  RS = 174;
  TS = 175;
  TSX = 176;
  RB = 177;
  RBI = 178;
  RBX = 179;
  RJS = 180;
  RABL = 181;
  RAKE = 182;
  CAPFILE = 183;
  JBUILDER = 184;
  GEMSPEC = 185;
  PODSPEC = 186;
  IRBRC = 187;
  PRYRC = 188;
  PRAWN = 189;
  THOR = 190;
  APPFILE = 191;
  APPRAISALS = 192;
  BERKSFILE = 193;
  BREWFILE = 194;
  CHEFFILE = 195;
  DELIVERFILE = 196;
  FASTFILE = 197;
  GEMFILE = 198;
  GUARDFILE = 199;
  PODFILE = 200;
  RAKEFILE = 201;
  RANTFILE = 202;
  SCANFILE = 203;
  SIMPLECOV = 204;
  SNAPFILE = 205;
  THORFILE = 206;
  VAGRANTFILE = 207;
  SCALA = 208;
  SBT = 209;
  SC = 210;
  CMD = 211;
  BAT = 212;
  COFFEE = 213;
  ERL = 214;
  HRL = 215;
  ESCRIPT = 216;
  LUA = 217;
  MD = 218;
  MDOWN = 219;
  MDWN = 220;
  MARKDOWN = 221;
  MARKDN = 222;
  MATLAB = 223;
  M = 224;
  PS1 = 225;
  SH = 226;
  BASH = 227;
  BASHRC = 228;
  ASH = 229;
  ZSH = 230;
  BASH_ALIASES = 231;
  BASH_COMPLETIONS = 232;
  BASH_FUNCTIONS = 233;
  BASH_LOGIN = 234;
  BASH_LOGOUT = 235;
  BASH_PROFILE = 236;
  BASH_VARIABLES = 237;
  PROFILE = 238;
  TEXTMATE_INIT = 239;
  ZLOGIN = 240;
  ZLOGOUT = 241;
  ZPROFILE = 242;
  ZSHENV = 243;
  ZSHRC = 244;
  PKGBUILD = 245;
  EBUILD = 246;
  ECLASS = 247;
  R = 248;
  SQL = 249;
  DDL = 250;
  DML = 251;
  TEX = 252;
  LTX = 253;
  STY = 254;
  CLS = 255;
  UNKNOWN = 256;
  YAML = 257;
  YML = 258;
  TOML = 259;
  TML = 260;
  CARGO_LOCK = 261;
  GOPKG_LOCK = 262;
  PIPFILE = 263;
  POETRY_LOCK = 264;
  UNIFORM_RESOURCE_LOCATOR = 265;
  CUSTOM_URL_SCHEME = 266;
  UNIX_FILE_PATH = 267;
  WINDOWS_FILE_PATH = 268;
  UNIFORM_RESOURCE_IDENTIFIER = 269;
  HLJS_1C = 270;
  HLJS_ABNF = 271;
  HLJS_ACCESSLOG = 272;
  HLJS_ACTIONSCRIPT = 273;
  HLJS_ADA = 274;
  HLJS_ANGELSCRIPT = 275;
  HLJS_APACHE = 276;
  HLJS_APPLESCRIPT = 277;
  HLJS_ARCADE = 278;
  HLJS_ARDUINO = 279;
  HLJS_ARMASM = 280;
  HLJS_ASCIIDOC = 281;
  HLJS_ASPECTJ = 282;
  HLJS_AUTOHOTKEY = 283;
  HLJS_AUTOIT = 284;
  HLJS_AVRASM = 285;
  HLJS_AWK = 286;
  HLJS_AXAPTA = 287;
  HLJS_BASH = 288;
  HLJS_BASIC = 289;
  HLJS_BNF = 290;
  HLJS_BRAINFUCK = 291;
  HLJS_CAL = 292;
  HLJS_CAPNPROTO = 293;
  HLJS_CEYLON = 294;
  HLJS_CLEAN = 295;
  HLJS_CLOJURE_REPL = 296;
  HLJS_CLOJURE = 297;
  HLJS_CMAKE = 298;
  HLJS_COFFEESCRIPT = 299;
  HLJS_COQ = 300;
  HLJS_COS = 301;
  HLJS_CPP = 302;
  HLJS_CRMSH = 303;
  HLJS_CRYSTAL = 304;
  HLJS_C = 305;
  HLJS_CS = 306;
  HLJS_CSP = 307;
  HLJS_CSS = 308;
  HLJS_D = 309;
  HLJS_DART = 310;
  HLJS_DELPHI = 311;
  HLJS_DIFF = 312;
  HLJS_DJANGO = 313;
  HLJS_DNS = 314;
  HLJS_DOCKERFILE = 315;
  HLJS_DOS = 316;
  HLJS_DSCONFIG = 317;
  HLJS_DTS = 318;
  HLJS_DUST = 319;
  HLJS_EBNF = 320;
  HLJS_ELIXIR = 321;
  HLJS_ELM = 322;
  HLJS_ERB = 323;
  HLJS_ERLANG_REPL = 324;
  HLJS_ERLANG = 325;
  HLJS_EXCEL = 326;
  HLJS_FIX = 327;
  HLJS_FLIX = 328;
  HLJS_FORTRAN = 329;
  HLJS_FSHARP = 330;
  HLJS_GAMS = 331;
  HLJS_GAUSS = 332;
  HLJS_GCODE = 333;
  HLJS_GHERKIN = 334;
  HLJS_GLSL = 335;
  HLJS_GML = 336;
  HLJS_GO = 337;
  HLJS_GOLO = 338;
  HLJS_GRADLE = 339;
  HLJS_GROOVY = 340;
  HLJS_HAML = 341;
  HLJS_HANDLEBARS = 342;
  HLJS_HASKELL = 343;
  HLJS_HAXE = 344;
  HLJS_HSP = 345;
  HLJS_HTMLBARS = 346;
  HLJS_HTTP = 347;
  HLJS_HY = 348;
  HLJS_INFORM7 = 349;
  HLJS_INI = 350;
  HLJS_IRPF90 = 351;
  HLJS_ISBL = 352;
  HLJS_JAVA = 353;
  HLJS_JAVASCRIPT = 354;
  HLJS_JBOSS_CLI = 355;
  HLJS_JSON = 356;
  HLJS_JULIA_REPL = 357;
  HLJS_JULIA = 358;
  HLJS_KOTLIN = 359;
  HLJS_LASSO = 360;
  HLJS_LDIF = 361;
  HLJS_LEAF = 362;
  HLJS_LESS = 363;
  HLJS_LISP = 364;
  HLJS_LIVECODESERVER = 365;
  HLJS_LIVESCRIPT = 366;
  HLJS_LLVM = 367;
  HLJS_LSL = 368;
  HLJS_LUA = 369;
  HLJS_MAKEFILE = 370;
  HLJS_MARKDOWN = 371;
  HLJS_MATHEMATICA = 372;
  HLJS_MATLAB = 373;
  HLJS_MAXIMA = 374;
  HLJS_MEL = 375;
  HLJS_MERCURY = 376;
  HLJS_MIPSASM = 377;
  HLJS_MIZAR = 378;
  HLJS_MOJOLICIOUS = 379;
  HLJS_MONKEY = 380;
  HLJS_MOONSCRIPT = 381;
  HLJS_N1QL = 382;
  HLJS_NGINX = 383;
  HLJS_NIMROD = 384;
  HLJS_NIX = 385;
  HLJS_NSIS = 386;
  HLJS_OBJECTIVEC = 387;
  HLJS_OCAML = 388;
  HLJS_OPENSCAD = 389;
  HLJS_OXYGENE = 390;
  HLJS_PARSER3 = 391;
  HLJS_PERL = 392;
  HLJS_PF = 393;
  HLJS_PGSQL = 394;
  HLJS_PHP = 395;
  HLJS_PLAINTEXT = 396;
  HLJS_PONY = 397;
  HLJS_POWERSHELL = 398;
  HLJS_PROCESSING = 399;
  HLJS_PROFILE = 400;
  HLJS_PROLOG = 401;
  HLJS_PROPERTIES = 402;
  HLJS_PROTOBUF = 403;
  HLJS_PUPPET = 404;
  HLJS_PUREBASIC = 405;
  HLJS_PYTHON = 406;
  HLJS_Q = 407;
  HLJS_QML = 408;
  HLJS_R = 409;
  HLJS_REASONML = 410;
  HLJS_RIB = 411;
  HLJS_ROBOCONF = 412;
  HLJS_ROUTEROS = 413;
  HLJS_RSL = 414;
  HLJS_RUBY = 415;
  HLJS_RULESLANGUAGE = 416;
  HLJS_RUST = 417;
  HLJS_SAS = 418;
  HLJS_SCALA = 419;
  HLJS_SCHEME = 420;
  HLJS_SCILAB = 421;
  HLJS_SCSS = 422;
  HLJS_SHELL = 423;
  HLJS_SMALI = 424;
  HLJS_SMALLTALK = 425;
  HLJS_SML = 426;
  HLJS_SQF = 427;
  HLJS_SQL = 428;
  HLJS_STAN = 429;
  HLJS_STATA = 430;
  HLJS_STEP21 = 431;
  HLJS_STYLUS = 432;
  HLJS_SUBUNIT = 433;
  HLJS_SWIFT = 434;
  HLJS_TAGGERSCRIPT = 435;
  HLJS_TAP = 436;
  HLJS_TCL = 437;
  HLJS_TEX = 438;
  HLJS_THRIFT = 439;
  HLJS_TP = 440;
  HLJS_TWIG = 441;
  HLJS_TYPESCRIPT = 442;
  HLJS_VALA = 443;
  HLJS_VBNET = 444;
  HLJS_VBSCRIPT_HTML = 445;
  HLJS_VBSCRIPT = 446;
  HLJS_VERILOG = 447;
  HLJS_VHDL = 448;
  HLJS_VIM = 449;
  HLJS_X86ASM = 450;
  HLJS_XL = 451;
  HLJS_XML = 452;
  HLJS_XQUERY = 453;
  HLJS_YAML = 454;
  HLJS_TOML = 455;
  HLJS_ZEPHIR = 456;
  HLJS_HTML = 457;
  GROOVY = 458;
  KT = 459;
  EL = 460;
  CLJ = 461;
  EX = 462;
  ADB = 463;
  ADS = 464;
  AGDA = 465;
  ELM = 466;
  EXS = 467;
  GLSL = 468;
  ML = 469;
  LEAN = 470;
  LISP = 471;
  RKT = 472;
  SPARQL = 473;
  VHDL = 474;
  ZIG = 475;
  DOCKERFILE = 476;
  F03 = 477;
  F08 = 478;
  F18 = 479;
  F90 = 480;
  F95 = 481;
  JL = 482;
  MM = 483;
  SCM = 484;
  SOL = 485;
  SV = 486;
  ASP = 487;
  CFM = 488;
  FS = 489;
  FSI = 490;
  FSX = 491;
  TF = 492;
  VBA = 493;
  SVELTE = 494;
  VUE = 495;
  SCSS = 496;
  FEATURE = 497;
  INI = 498;
  FTL = 499;
  HCL = 500;
  ABAP = 501;
}

message CodeLanguageDetectionDistribution {
  repeated double value = 1;
}

message CodeLanguageDetection {
  runtime.aot.core.Cancellation cancellation = 1;
  CodeLanguageDetectionType type = 2;
  CodeLanguageDetectionDistribution distribution = 3;
}

// ========================================================================
// Initialized Class.
// ========================================================================

message VertexCodeLanguageDetectorInitialization {
}


message InitializedVertexCodeLanguageDetector {
}
