syntax = "proto3";

import "lib/src/core/root/grpc/shared/models/cancellation.proto";
import "lib/src/core/root/grpc/shared/models/user.proto";

package runtime.aot.machine_learning.text.technical_language.code.descriptors.appellation.vertex;

message UntitledCode {
  // Code Input
  string value = 1;
  // optional user
  runtime.aot.core.UserProfile user = 2;
  // note: this is the os_identifier
  string os = 3;
}

message TitledCode {
  runtime.aot.core.Cancellation cancellation = 1;
  // Title Output
  string value = 2;
}

// ========================================================================
// Initialized Class.
// ========================================================================

message VertexCodeAppellationDescriptorInitialization {
}


message InitializedVertexCodeAppellationDescriptor {
}
