syntax = "proto3";

import "lib/src/google/protobuf/timestamp.proto";
import "lib/src/core/root/grpc/shared/models/cancellation.proto";
import "lib/src/google/protobuf/duration.proto";

package runtime.aot.core;

// Health Check Request - Standard gRPC health checking protocol
message HealthCheckRequest {
  string service = 1;
}

enum HealthCheckServingStatus {
    UNKNOWN = 0;
    SERVING = 1;
    NOT_SERVING = 2;
    SERVICE_UNKNOWN = 3;  // Used only by the Watch method.
}

// Health Check Response - Standard gRPC health checking protocol
message HealthCheckResponse {
  HealthCheckServingStatus status = 1;
}