syntax = "proto3";

import "lib/src/core/root/grpc/shared/models/cancellation.proto";

// TODO change your models && your package.
package runtime.aot.data.structures.node.structure;


enum NodeInformationObjective {
  TAG = 0;
  TITLE = 1;
  SUBTITLE = 2;
  SUMMARIZE = 3;
  EXPLAIN = 4;
  COMMENT = 5;
  DOCUMENT = 6;
  REFERENCE = 7; // i.e. a website or file path path
}

// Information Level is the amount of information that is perceived by a user
enum NodeInformationLevel {
  // Tag i.e. (1-3 words)
  TAGIFICATION = 0;
  // Title i.e. (3-6 words)
  APPELLATION = 1;
  // Summary i.e. (2-5 sentences)
  SUMMARIZATION = 2;
  // Explanation i.e. (2-n paragraphs)
  EXPLANATION = 3;
  // Comment i.e. (1-5 Sentences)
  COMMENTATION = 4;
  // Documentation i.e. (n-n pages)
  DOCUMENTATION = 5;
  // REFERRAL i.e. a website or path
  REFERRAL = 6;
}

enum NodeInformationType {
  TEXTUAL = 0;
  VISUAL = 1;
}

message NodeInformation {
  NodeInformationLevel level = 1;
  NodeInformationObjective objective = 2;
  NodeInformationType type = 3;
}

enum NodeMaterialPackaging {
  FILE = 0;
  FRAGMENT = 1;
  DIRECTORY = 2;
}

enum NodeMaterialRendering {
  HTML = 0;
  DYNAMIC = 1;
}

enum NodeMaterialGenericClassification {
  TEXT = 0;
  IMAGE = 1;
  VIDEO = 2;
  AUDIO = 3;
  CODE = 4;
  DATA = 5;
  EXTERNAL_RESOURCE_REFERENCE = 6;
}

enum NodeMaterialSpecificClassification {
  // GENERIC TEXT SPECIFIC CLASSIFICATIONS
  PLAIN = 0; // i.e. mime type text/plain
  // ADDING EXT TO FILE EXTENSIONS TO HELP WITH SCOPING CONFLICTS WITH OTHER ENUMS I.E.
  // CANT USE TEXT BC ITS A GENERIC CLASSIFICATION
  TXT_EXT = 1; // .txt
  TEXT_EXT = 2; // .text

  // GENERIC EXTERNAL_RESOURCE_REFERENCE SPECIFIC CLASSIFICATIONS
  UNIFORM_RESOURCE_LOCATOR = 3; // URL
  UNIFORM_RESOURCE_IDENTIFIER = 4; // URI
  CUSTOM_URL_SCHEME = 5; // CUSTOM URL SCHEME I.E. "APP://"
  UNIX_FILE_PATH = 6; // UNIX FILE PATH I.E. "/home/user/file.txt"
  WINDOWS_FILE_PATH = 7; // WINDOWS FILE PATH I.E. "C:\Users\user\file.txt"

  // GENERIC IMAGE SPECIFIC CLASSIFICATIONS
  PNG = 8;
}

message NodeMaterialClassification {
  NodeMaterialGenericClassification generic = 1;
  NodeMaterialSpecificClassification specific = 2;
}


message NodeMaterialOrigin {
  //  message application = 1;
  //  message project = 2;
  //  message platform = 3;
  //  message framework = 4;
}


enum NodeMaterialDomain {
  // Natural Language
  UNKNOWN = 0;
  // Technical Language
  SOFTWARE = 1;
  // Design Language
  DESIGN = 2;
  // etc. tbd...
}

message NodeMaterial {
  NodeMaterialPackaging packaging = 1;
  NodeMaterialRendering rendering = 2;
  NodeMaterialOrigin origin = 3;
  NodeMaterialClassification classification = 4;
  NodeMaterialDomain domain = 5;
}

// This is similar to our transferable models from before
message NodeData {
  string string = 1;
  string bytes = 2;
  string base64 = 3;
  // etc. tbd...
}

enum EdgesHierarchy {
  DETACHED = 0;
  LEAF = 1; // I.e. When Creating Stand Alone Metadata Structure, LEAF would be used to represent a node that is not associated with any other node, but can be associated with a parent
  INTERMEDIATE = 2; // i.e. When Creating a Stand Alone Item, INTERMEDIATE would be used to represent the item itself, and its child would be the metadata
  ROOT = 3; // i.e. When Creating a Stand Alone Collection, ROOT would be used to represent the collection itself, and its child would be the item
}

message NodeIdentity {
  double uuid = 1;
  int32 identifier = 2;
}


message NodeEdge {
  NodeIdentity identity = 1;
}

message NodeGraphIdentity {
  double uuid = 1;
  int32 identifier = 2;
}

message LeafNodeGraphEdges {
  NodeGraphIdentity identity = 1;

  // This can be thought of as the data node for this graph
  NodeEdge node = 2;
  repeated NodeEdge nodes = 3;

  repeated IntermediateNodeGraphEdges intermediates = 4;
}

message IntermediateNodeGraphEdges {
  NodeGraphIdentity identity = 1;

  // This can be thought of as the data node for this graph
  NodeEdge node = 2;
  repeated NodeEdge nodes = 3;

  repeated LeafNodeGraphEdges leafs = 4;

}

message RootNodeGraphEdges {
  NodeGraphIdentity identity = 1;

  // This can be thought of as the data node for this graph
  NodeEdge node = 2;
  repeated NodeEdge nodes = 3;
  repeated LeafNodeGraphEdges leafs = 4;
  repeated IntermediateNodeGraphEdges intermediates = 5;

}


// Edges can point to a node itself or a node graph
message Edges {
  NodeEdge node = 1;

  RootNodeGraphEdges root = 2;
  IntermediateNodeGraphEdges intermediate = 3;
  LeafNodeGraphEdges leaf = 4;

  // These represent graphs
  repeated RootNodeGraphEdges roots = 5;
  repeated IntermediateNodeGraphEdges intermediates = 6;
  repeated LeafNodeGraphEdges leafs = 7;
}

message Node {
  NodeIdentity identity = 1;
  NodeInformation information = 2;
  NodeMaterial material = 3;
  NodeData data = 4;

  // Edges point to other nodes and node graphs
  Edges edges = 5;
  // TODO Add in Edges Depth
  // TODO Depth?
}

message SeededNode {
  NodeInformation information = 1;
  NodeMaterial material = 2;
  NodeData data = 3;
  // TODO perhaps this will have edges on here as well ?
  // TODO Depth?
}